export const PACKAGE_NAME = "gpio-companion";
export const VERSION = "0.0.0";

export function greet(from = PACKAGE_NAME): string {
	return `hello from ${from}`;
}

export {
	AGENT_LOG_MAX,
	AGENT_PATH,
	AGENT_PROMPT_MAX,
	AGENT_STOP_PATH,
	AgentError,
	type AgentPut,
	type AgentResult,
	type AgentStatus,
	capAgentLog,
	isAgentPath,
	parseAgentPut,
} from "./agent.ts";
export { hashAiKey } from "./ai-key.ts";
export {
	applyMarkup,
	costMicrodollars,
	DEFAULT_AI_MARKUP,
	DEFAULT_AI_MODEL,
	DEFAULT_EMBEDDING_MODEL,
	DEFAULT_MAX_COMPLETION_TOKENS,
	type EmbeddingModelInfo,
	embeddingCostMicrodollars,
	embeddingModelInfo,
	estimateEmbeddingTokens,
	estimatePromptTokens,
	formatUsd,
	LEGACY_CREDIT_MICROS,
	llmModelDisplayName,
	llmModelReasoning,
	MAX_EMBEDDING_INPUTS,
	type ModelRate,
	microsToUsd,
	modelRate,
	type OpenAiModelListItem,
	type OpencodeProviderModel,
	openaiChatModelList,
	opencodeProviderModels,
	parseMarkup,
	REASONING_EFFORTS,
	type ReasoningEffort,
	type TokenUsage,
	tokensToMicrodollars,
	USD_MICROS,
	usdToMicros,
	WORKERS_AI_EMBEDDING_RATES,
	WORKERS_AI_LLM_RATES,
	WORKERS_AI_LLM_REASONING,
} from "./ai-pricing.ts";
export {
	AI_TOKEN_PREFIX,
	AI_TOKEN_TTL_MS,
	type AiAccessClaims,
	isAiAccessToken,
	signAiAccessToken,
	verifyAiAccessToken,
} from "./ai-token.ts";
export {
	ARDUINO_PROXY_BOARDS,
	ARDUINO_PROXY_FQBNS,
	ARDUINO_PROXY_LIB_DIR,
	ARDUINO_PROXY_PATH,
	ARDUINO_PROXY_SKETCH_PREFIX,
	type ArduinoProxyBoard,
	type ArduinoProxyBoardId,
	type ArduinoProxyBuses,
	ArduinoProxyError,
	type ArduinoProxyFamily,
	type ArduinoProxyPinDef,
	type ArduinoProxyStatus,
	type ArduinoProxyVoltage,
	arduinoCoreForFqbn,
	arduinoProxyBaud,
	arduinoProxyBoard,
	arduinoProxyPins,
	arduinoProxySketchName,
	arduinoProxySnapshot,
	ESP32_BOARD_MANAGER_URL,
	emptyArduinoProxyStatus,
	FIRMWARE_BAUD_AVR,
	FIRMWARE_BAUD_ESP32,
	type FlashProxyPut,
	isArduinoProxyFqbn,
	isArduinoProxyPath,
	isArduinoProxySketchName,
	normalizeFqbn,
	parseArduinoCoreList,
	parseArduinoProxyStatus,
	parseFlashProxyPut,
} from "./arduino-proxy.ts";
export {
	type ArduinoHeaderLayout,
	type ArduinoLayoutSeat,
	arduinoProxyHeaderLayout,
} from "./arduino-proxy-layout.ts";
export {
	BLE_CHUNK_SIZE,
	BLE_CMD_UUID,
	BLE_DEVICE_NAME,
	BLE_INFO_UUID,
	BLE_SERVICE_UUID,
	BLE_STATUS_UUID,
	type BleInfo,
	createBleAssembler,
	createSignedEnvelope,
	envelopeToPasteText,
	envelopeToRequest,
	ingestBleStatus,
	isBleCompleteStatus,
	isBleIdleStatus,
	isBlePartialSnapshot,
	isBleSettledStatus,
	parseSignedEnvelope,
	type SignedDeviceEnvelope,
	splitBleFrames,
} from "./ble.ts";
export {
	BLE_HEALTH_CHECKS,
	BLE_HEALTH_WIFI_PSK,
	BLE_HEALTH_WIFI_SSID,
	type BleHealthCheck,
	type BleHealthCheckId,
	type BleHealthReportRow,
	type BleHealthVerdict,
	bleHealthErrorMessage,
	evaluateBleHealthCheck,
	formatBleHealthReport,
	parseBleHealthBody,
} from "./ble-health.ts";
export {
	type BoardSeedEntry,
	type BoardSeedManifest,
	familyFallbackSeed,
	normalizeBoardModel,
	parseBoardSeedManifest,
	type ResolvedBoardSeed,
	resolveBoardSeed,
} from "./board-seeds.ts";
export {
	BREADBOARD_DIAGRAM_JSON,
	BREADBOARD_LEFT_COLS,
	BREADBOARD_PITCH,
	BREADBOARD_RAILS,
	BREADBOARD_RIGHT_COLS,
	BreadboardError,
	type BreadboardStep,
	boardPinAbsolute,
	breadboardHasRails,
	breadboardLayoutShift,
	breadboardPinNames,
	breadboardPinOffset,
	breadboardRows,
	breadboardSize,
	GPIO_ARDUINO_PROXY_TYPE,
	GPIO_COMPANION_HEADER_TYPE,
	HEADER_EVEN_X,
	HEADER_ODD_X,
	HEADER_ORIGIN_Y,
	HEADER_PIN_COUNT,
	headerPinCount,
	headerPinOffset,
	headerSize,
	isBreadboardType,
	netPartIds,
	type PartPinInfo,
	type PartPlacement,
	type Point,
	parseWokwiDiagram,
	partOrigin,
	partPinsFor,
	rotatePoint,
	snapPartPlacement,
	splitEndpoint,
	WOKWI_BREADBOARD_TYPES,
	type WokwiConnection,
	type WokwiDiagram,
	type WokwiPart,
	wirePath,
} from "./breadboard.ts";
export {
	type ArduinoProxyBoardLayout,
	type ArduinoProxyPad,
	type ArduinoProxyPadKind,
	arduinoProxyBoardLayout,
	arduinoProxyBoardSize,
	arduinoProxyBoardTitle,
	arduinoProxyPadOffset,
	arduinoProxyPads,
	arduinoProxyPinOffset,
	arduinoProxyResolvePad,
	isArduinoProxyPartType,
} from "./breadboard-arduino.ts";
export {
	type DeviceConfig,
	emptyDeviceConfig,
	emptyTunnelConfig,
	HARDWARE_IDS,
	type HardwareId,
	isHardwareId,
	parseDeviceConfig,
	parseTunnelConfig,
	redactDeviceConfig,
	type TunnelConfig,
} from "./config.ts";
export {
	applyConsoleMessage,
	asConsoleWsError,
	CONSOLE_BAUDS,
	CONSOLE_DEFAULT_BAUD,
	CONSOLE_FLUSH_MS,
	CONSOLE_LOG_MAX,
	CONSOLE_MAX_SOCKETS,
	CONSOLE_PATH,
	CONSOLE_USB_PATH,
	CONSOLE_USB_REOPEN_MS,
	CONSOLE_USB_STOP_PATH,
	type ConsoleBaud,
	type ConsoleChunk,
	ConsoleError,
	type ConsoleFrame,
	type ConsoleHostRunning,
	type ConsoleHostState,
	type ConsoleSnapshot,
	type ConsoleSource,
	type ConsoleUsbOpen,
	type ConsoleUsbPut,
	type ConsoleUsbState,
	type ConsoleWsError,
	type ConsoleWsRefresh,
	capConsoleLog,
	consoleWsConnectUrl,
	consoleWsUrl,
	emptyConsoleSnapshot,
	isConsolePath,
	parseConsoleUsbPut,
	parseConsoleWsCommand,
} from "./console.ts";
export {
	DEBUG_EVENT_PATH,
	DEBUG_LIVE_TTL_SEC,
	DEBUG_MAX_SOCKETS,
	DEBUG_PATH,
	DEBUG_RING_SIZE,
	DEBUG_UPGRADE_FAILED,
	DEBUG_VIA_HEADER,
	DEFAULT_DASHBOARD_ORIGIN,
	type DebugEvent,
	type DebugLevel,
	type DebugProbe,
	type DebugVia,
	debugAuthHeadersFromRequest,
	debugAuthHeadersFromSearch,
	debugAuthQuery,
	debugLevelFromStatus,
	debugProbeMessage,
	debugViaFromRequest,
	debugWsConnectUrl,
	debugWsUrl,
	formatDebugLogLine,
	isAllowedDebugOrigin,
	isLiveSeen,
	liveDeviceUrl,
	normalizeDebugPath,
	parseDebugEvent,
	parseDebugEventInput,
	parseDebugProbe,
	parseLivePingUuid,
	redactDebugMessage,
	shouldPublishDebugPath,
} from "./debug.ts";
export {
	canonicalDevicePayload,
	DEFAULT_DEVICE_MAX_SKEW_MS,
	DEVICE_AUTH_HEADERS,
	DEVICE_AUTH_VERSION,
	DeviceAuthError,
	type DeviceAuthHeaders,
	type DeviceKeyPair,
	type DeviceVerifyResult,
	generateDeviceKeyPair,
	hasDeviceSignature,
	normalizeDevicePath,
	publicKeyPemFromPrivateKey,
	signDeviceRequest,
	signEd25519Message,
	verifyDeviceRequest,
	verifyEd25519Message,
} from "./device-auth.ts";
export {
	type DeviceEndpointAuth,
	type DeviceEndpointExpect,
	type DeviceEndpointProbe,
	type DeviceEndpointVerdict,
	type DeviceEndpointVia,
	deviceEndpointErrorMessage,
	deviceEndpointProbes,
	evaluateDeviceEndpointProbe,
	parseDeviceEndpointBody,
} from "./device-endpoint-runner.ts";
export {
	type DeviceInfoRow,
	flattenDeviceInfo,
	formatNetworkLabel,
	INFO_PATH,
	type NetworkConnectionType,
	type NetworkStatus,
	parseNetworkStatus,
} from "./device-info.ts";
export { DEFAULT_DEVICE_KEY_ID } from "./device-public-key.ts";
export {
	createFirmataParser,
	encodeAnalogMappingQuery,
	encodeAnalogWrite,
	encodeCapabilityQuery,
	encodeDigitalPin,
	encodeI2cConfig,
	encodeI2cRead,
	encodeI2cScan,
	encodeI2cWrite,
	encodeQueryFirmware,
	encodeReportAnalog,
	encodeReportDigital,
	encodeSerialListen,
	encodeSerialWrite,
	encodeSetPinMode,
	encodeSpiTransfer,
	encodeSysex,
	encodeSystemReset,
	type FirmataEvent,
	type FirmataPinCapability,
	type FirmataPinMode,
	firmataModeCode,
	PIN_MODE_ANALOG,
	PIN_MODE_I2C,
	PIN_MODE_IGNORE,
	PIN_MODE_INPUT,
	PIN_MODE_OUTPUT,
	PIN_MODE_PULLUP,
	PIN_MODE_PWM,
	PIN_MODE_SERIAL,
	PIN_MODE_SPI,
	parseFirmataBytes,
	REPORT_VERSION,
	SET_PIN_MODE,
	START_SYSEX,
	SYSEX_CAPABILITY_QUERY,
	SYSEX_I2C_REPLY,
	SYSEX_REPORT_FIRMWARE,
} from "./firmata.ts";
export {
	capFlashLog,
	FLASH_LOG_MAX,
	FLASH_PATH,
	FLASH_PORTS_PATH,
	FLASH_PROXY_PATH,
	FLASH_SKETCHES_PATH,
	FlashError,
	type FlashPort,
	type FlashPut,
	type FlashResult,
	type FlashStatus,
	isFlashPath,
	parseArduinoBoardList,
	parseFlashPut,
} from "./flash.ts";
export {
	createGithubAppJwt,
	GITHUB_API,
	GITHUB_APP_TOKEN_PREFIX,
	GITHUB_GIT_USER,
	gitHttpsUsername,
	isGithubAppToken,
	timingSafeEqualString,
} from "./github-app.ts";
export {
	type GithubAppCallback,
	isGithubAppOAuthIssuer,
	parseGithubAppCallbackFromUrl,
	parseGithubAppCallbackSearch,
} from "./github-app-callback.ts";
export {
	analogToPwmPercent,
	applyGpioApply,
	applyGpioMessage,
	asGpioPatch,
	asGpioWsError,
	assertGpioDrive,
	canDriveGpio,
	GPIO_ANALOG_MAX,
	GPIO_MAX_PWM,
	GPIO_MAX_SOCKETS,
	GPIO_PATH,
	GPIO_PWM_HZ,
	GPIO_RESERVED_PHYSICAL,
	GPIO_STREAM_MS,
	type GpioApply,
	type GpioBusCommand,
	type GpioDir,
	GpioError,
	type GpioNoTone,
	type GpioPatch,
	type GpioPinState,
	type GpioPinTone,
	type GpioProxyInfo,
	type GpioPut,
	type GpioSnapshot,
	type GpioStreamFrame,
	type GpioTarget,
	type GpioTone,
	type GpioWsCommand,
	type GpioWsRefresh,
	gpioLiveValues,
	gpioNamedLine,
	gpioPatchFrame,
	gpioPinOff,
	gpioPinStatusKey,
	gpioPinStatusLabel,
	gpioPinTone,
	gpioSnapshotStatusKey,
	gpioWsConnectUrl,
	gpioWsUrl,
	HEADER_PIN_PAIRS,
	type HeaderPinDef,
	type HeaderPinType,
	headerPin,
	headerPinPairs,
	headerPins,
	headerPinsForBoard,
	isGpioBusCommand,
	isGpioNoTone,
	isGpioTone,
	isGpioWsRefresh,
	parseGpioPut,
	parseGpioTarget,
	parseGpioWsCommand,
	parsePhysicalPin,
	pinByPhysical,
} from "./gpio.ts";
export {
	type GpioChipSize,
	parseGpioChips,
	resolveSkuChip,
	type SkuGpioDomain,
	type SkuGpioLine,
	type SkuPinout,
	skuPinout,
} from "./gpio-sku.ts";
export {
	asArduinoProxyStatus,
	asFlashStatus,
	asGpioSnapshot,
	asHubT3Status,
	asRunStatus,
	encodeHubMessage,
	HUB_FLASH_MS,
	HUB_GPIO_MS,
	HUB_LIVE_TTL_SEC,
	HUB_PATH,
	HUB_PING_MS,
	HUB_PROXY_MS,
	HUB_RUN_MS,
	HUB_T3_MS,
	HUB_TOKEN_PREFIX,
	HUB_TOKEN_TTL_MS,
	type HubChannel,
	type HubMessage,
	type HubMessageType,
	type HubRole,
	type HubT3Status,
	type HubTicket,
	type HubTicketClaims,
	hubOrigin,
	hubWsUrl,
	isHubAccessToken,
	isHubChannel,
	isHubRole,
	parseHubMessage,
	signHubTicket,
	verifyHubTicket,
} from "./hub.ts";
export {
	capLogText,
	DEBUG_MAINTENANCE_PATH,
	DEBUG_MAINTENANCE_TTL_SEC,
	type DiskStats,
	filterJournalByAge,
	formatDiskFree,
	JOURNAL_WINDOWS,
	type JournalWindowId,
	journalWindowMs,
	LOG_JOURNAL_UNITS,
	LOGS_MAX_BYTES,
	LOGS_MAX_LINES,
	LOGS_PATH,
	LOGS_SINCE_HOURS,
	type MaintenanceReport,
	parseDiskStats,
	parseJournalTimestamp,
	parseMaintenanceReport,
	redactLogText,
	UPDATE_PATH,
} from "./maintenance.ts";
export {
	canonicalOfflineGrant,
	envelopeGrant,
	grantHeaderValue,
	isOfflineGrantScope,
	mintOfflineGrant,
	OFFLINE_GRANT_REFRESH_MS,
	OFFLINE_GRANT_SCOPE,
	OFFLINE_GRANT_TTL_MS,
	OFFLINE_GRANT_VERSION,
	type OfflineGrant,
	type OfflineGrantBundle,
	type OfflineGrantScope,
	offlineGrantNeedsRefresh,
	offlineScopeKey,
	parseOfflineEnvelope,
	parseOfflineGrant,
	signOfflineEnvelope,
	verifyOfflineEnvelope,
	verifyOfflineGrant,
	WIFI_PATH,
} from "./offline-grant.ts";
export {
	emptyPairingState,
	loginFromEmail,
	type PairingClaim,
	type PairingCredentials,
	type PairingPublic,
	type PairingState,
	pairingCredentials,
	parsePairingClaim,
	parsePairingUnpair,
	publicPairing,
} from "./pairing.ts";
export {
	BREADBOARD_CIRCUIT_JSON,
	BREADBOARD_PREVIEW_SVG,
	FIRMWARE_SKETCH_DIR,
	githubCloneUrl,
	githubOriginMatches,
	HOST_SKETCH_DIR,
	isProjectFileDir,
	MAX_PROJECT_WATERMARK_CHECKS,
	PCB_CIRCUIT_JSON,
	PCB_PREVIEW_SVG,
	PROJECT_FILE_DIRS,
	PROJECT_PUSH_GIT_EMAIL,
	PROJECT_PUSH_GIT_NAME,
	PROJECT_PUSH_MESSAGE,
	PROJECT_PUSH_MESSAGE_MAX,
	PROJECT_REPO_DESCRIPTION,
	PROJECT_WATERMARK_BODY,
	PROJECT_WATERMARK_PATH,
	PROJECTS_DIR_NAME,
	PROJECTS_PUSH_PATH,
	PROJECTS_REMOVE_PATH,
	PROJECTS_SYNC_PATH,
	type ProjectFileDir,
	type ProjectPushPut,
	type ProjectPushResult,
	type ProjectRemovePut,
	type ProjectSyncPut,
	type ProjectWatermarkCandidate,
	parseGithubRepoName,
	parseProjectPushPut,
	parseProjectRemovePut,
	parseProjectSyncPut,
	pickProjectWatermarkCandidates,
	SKETCH_LIST_MAX,
} from "./project-files.ts";
export {
	capRunLog,
	isRunPath,
	parseRunPut,
	RUN_LOG_MAX,
	RUN_PATH,
	RUN_SKETCHES_PATH,
	RUN_STOP_PATH,
	RunError,
	type RunPut,
	type RunResult,
	type RunStatus,
} from "./run.ts";
export {
	DEFAULT_GITHUB_URL,
	type DeviceSecrets,
	emptyDeviceSecrets,
	mergeDeviceSecrets,
	parseDeviceSecrets,
	secretsStatus,
} from "./secrets.ts";
export {
	type BoardSketch,
	type BoardSketchKind,
	type BoardSketchList,
	parseBoardSketchList,
	sketchKindDir,
} from "./sketches.ts";
export {
	cloudflareTunnelName,
	DASHBOARD_ORIGIN,
	DEVICE_API_PORT,
	dashboardT3PairPath,
	dashboardT3PairUrl,
	extractT3PairingToken,
	extractT3PairingUrl,
	pairingSlug,
	pairingUuidFromDeviceUrl,
	parseDashboardT3PairLocation,
	publicDeviceUrl,
	rewriteT3PairingUrl,
	T3_DASHBOARD_PATH,
	T3_ORIGIN_PORT,
	TUNNEL_ZONE,
	type TunnelHostnames,
	t3PairPageUrl,
	tunnelHostnames,
} from "./tunnel-host.ts";
export {
	type CircuitNet,
	type CircuitVerifyItem,
	type CircuitVerifyKind,
	type CircuitVerifyOverlay,
	type CircuitVerifyPut,
	type CircuitVerifyResult,
	type CircuitVerifyState,
	type CircuitVerifyStatus,
	circuitVerifyColor,
	circuitVerifyLabel,
	circuitVerifyOverlay,
	circuitVerifyPlan,
	expandCircuitNets,
	isVerifyPath,
	parseVerifyPut,
	VERIFY_PATH,
	VERIFY_PULSE_MS,
	VERIFY_STOP_PATH,
	VerifyError,
} from "./verify.ts";
export {
	encodeVoiceMessage,
	isVoiceAccessToken,
	isVoiceMicMode,
	foldWakeText,
	matchesWakePhrase,
	parseVoiceClientMessage,
	parseVoiceId,
	parseVoiceMicMode,
	parseVoiceServerMessage,
	signVoiceTicket,
	VOICE_BILL_MS,
	VOICE_GROK_TOOLS,
	VOICE_ID_STORAGE_KEY,
	VOICE_MIC_STORAGE_KEY,
	VOICE_MODEL,
	VOICE_PATH,
	VOICE_S2S_USD_PER_MIN,
	VOICE_SAMPLE_RATE,
	VOICE_SPEAKERS,
	VOICE_TOKEN_PREFIX,
	VOICE_TOKEN_TTL_MS,
	VOICE_VOICE_ID,
	type VoiceClientMessage,
	type VoiceClientType,
	type VoiceGrokFunctionTool,
	type VoiceMicMode,
	type VoiceServerMessage,
	type VoiceServerType,
	type VoiceSpeaker,
	type VoiceTicket,
	type VoiceTicketClaims,
	verifyVoiceTicket,
	voiceGrokInstructions,
	voiceKeyterms,
	voiceOrigin,
	voiceSessionMicros,
	voiceWsUrl,
	WAKE_PHRASE,
	WAKE_PHRASE_LABEL,
} from "./voice.ts";
export {
	classifyWifiConnectError,
	parseWifiConfig,
	publicWifiFailure,
	publicWifiStatus,
	type WifiConfig,
	WifiConnectError,
	type WifiConnectReason,
	wifiConnectMessage,
	wifiDevicesToClaim,
} from "./wifi.ts";
