export const PACKAGE_NAME = "gpio-companion";
export const VERSION = "0.0.0";

export function greet(from = PACKAGE_NAME): string {
	return `hello from ${from}`;
}

export { hashAiKey } from "./ai-key.ts";
export {
	applyMarkup,
	costMicrodollars,
	DEFAULT_AI_MARKUP,
	DEFAULT_AI_MODEL,
	DEFAULT_EMBEDDING_MODEL,
	DEFAULT_MAX_COMPLETION_TOKENS,
	type EmbeddingModelInfo,
	embeddingCostMicrodollars,
	embeddingModelInfo,
	estimateEmbeddingTokens,
	estimatePromptTokens,
	formatUsd,
	LEGACY_CREDIT_MICROS,
	MAX_EMBEDDING_INPUTS,
	type ModelRate,
	microsToUsd,
	modelRate,
	parseMarkup,
	type TokenUsage,
	tokensToMicrodollars,
	USD_MICROS,
	usdToMicros,
	WORKERS_AI_EMBEDDING_RATES,
	WORKERS_AI_LLM_RATES,
} from "./ai-pricing.ts";
export {
	BLE_CHUNK_SIZE,
	BLE_CMD_UUID,
	BLE_DEVICE_NAME,
	BLE_INFO_UUID,
	BLE_SERVICE_UUID,
	BLE_STATUS_UUID,
	type BleInfo,
	createBleAssembler,
	createSignedEnvelope,
	envelopeToPasteText,
	envelopeToRequest,
	parseSignedEnvelope,
	type SignedDeviceEnvelope,
	splitBleFrames,
} from "./ble.ts";
export {
	type BoardSeedEntry,
	type BoardSeedManifest,
	familyFallbackSeed,
	normalizeBoardModel,
	parseBoardSeedManifest,
	type ResolvedBoardSeed,
	resolveBoardSeed,
} from "./board-seeds.ts";
export {
	BREADBOARD_DIAGRAM_JSON,
	BREADBOARD_PITCH,
	BreadboardError,
	type BreadboardStep,
	breadboardPinOffset,
	breadboardRows,
	breadboardSize,
	GPIO_COMPANION_HEADER_TYPE,
	HEADER_PIN_COUNT,
	headerPinOffset,
	headerSize,
	isBreadboardType,
	type Point,
	parseWokwiDiagram,
	partOrigin,
	rotatePoint,
	splitEndpoint,
	WOKWI_BREADBOARD_TYPES,
	type WokwiConnection,
	type WokwiDiagram,
	type WokwiPart,
	wirePath,
} from "./breadboard.ts";
export {
	type DeviceConfig,
	emptyDeviceConfig,
	emptyTunnelConfig,
	HARDWARE_IDS,
	type HardwareId,
	isHardwareId,
	parseDeviceConfig,
	parseTunnelConfig,
	redactDeviceConfig,
	type TunnelConfig,
} from "./config.ts";
export {
	DEBUG_LIVE_PATH,
	DEBUG_LIVE_PING_MS,
	DEBUG_LIVE_TTL_SEC,
	DEBUG_MAX_SOCKETS,
	DEBUG_PATH,
	DEBUG_RING_SIZE,
	DEBUG_UPGRADE_FAILED,
	DEFAULT_DASHBOARD_ORIGIN,
	type DebugEvent,
	type DebugLevel,
	type DebugProbe,
	debugAuthHeadersFromRequest,
	debugAuthHeadersFromSearch,
	debugAuthQuery,
	debugLevelFromStatus,
	debugProbeMessage,
	debugWsConnectUrl,
	debugWsUrl,
	isAllowedDebugOrigin,
	isLiveSeen,
	liveDeviceUrl,
	normalizeDebugPath,
	parseDebugEvent,
	parseDebugProbe,
	parseLivePingUuid,
	redactDebugMessage,
	shouldPublishDebugPath,
} from "./debug.ts";
export {
	canonicalDevicePayload,
	DEFAULT_DEVICE_MAX_SKEW_MS,
	DEVICE_AUTH_HEADERS,
	DEVICE_AUTH_VERSION,
	DeviceAuthError,
	type DeviceAuthHeaders,
	type DeviceKeyPair,
	type DeviceVerifyResult,
	generateDeviceKeyPair,
	normalizeDevicePath,
	publicKeyPemFromPrivateKey,
	signDeviceRequest,
	verifyDeviceRequest,
} from "./device-auth.ts";
export { DEFAULT_DEVICE_KEY_ID } from "./device-public-key.ts";
export {
	createGithubAppJwt,
	GITHUB_API,
	GITHUB_APP_TOKEN_PREFIX,
	GITHUB_GIT_USER,
	gitHttpsUsername,
	isGithubAppToken,
	timingSafeEqualString,
} from "./github-app.ts";
export {
	emptyPairingState,
	loginFromEmail,
	type PairingClaim,
	type PairingCredentials,
	type PairingPublic,
	type PairingState,
	pairingCredentials,
	parsePairingClaim,
	parsePairingUnpair,
	publicPairing,
} from "./pairing.ts";
export {
	BREADBOARD_CIRCUIT_JSON,
	BREADBOARD_PREVIEW_SVG,
	isProjectFileDir,
	PCB_CIRCUIT_JSON,
	PCB_PREVIEW_SVG,
	PROJECT_FILE_DIRS,
	type ProjectFileDir,
} from "./project-files.ts";
export {
	DEFAULT_GITHUB_URL,
	type DeviceSecrets,
	emptyDeviceSecrets,
	mergeDeviceSecrets,
	parseDeviceSecrets,
	secretsStatus,
} from "./secrets.ts";
export {
	cloudflareTunnelName,
	DEVICE_API_PORT,
	extractT3PairingToken,
	extractT3PairingUrl,
	pairingSlug,
	publicDeviceUrl,
	rewriteT3PairingUrl,
	T3_ORIGIN_PORT,
	TUNNEL_ZONE,
	type TunnelHostnames,
	tunnelHostnames,
} from "./tunnel-host.ts";
export {
	classifyWifiConnectError,
	parseWifiConfig,
	publicWifiFailure,
	publicWifiStatus,
	type WifiConfig,
	WifiConnectError,
	type WifiConnectReason,
	wifiConnectMessage,
} from "./wifi.ts";
