const files = {
	gettingStarted: new URL("../../../documentation/user/getting-started.md", import.meta.url),
	userGuide: new URL("../../../documentation/user/README.md", import.meta.url),
	wifiBluetooth: new URL("../../../documentation/user/wifi-bluetooth.md", import.meta.url),
	storage: new URL("../../../documentation/user/storage.md", import.meta.url),
	workflows: new URL("../../../documentation/user/workflows.md", import.meta.url),
	pinoutOrange: new URL(
		"../../../opencode/skills/gpio-pinout-orangepi/SKILL.md",
		import.meta.url,
	),
	pinoutRaspberry: new URL(
		"../../../opencode/skills/gpio-pinout-raspberrypi/SKILL.md",
		import.meta.url,
	),
};

const out = ["// Generated by scripts/bundle-docs.ts — do not edit by hand.", ""];
for (const [name, path] of Object.entries(files)) {
	const raw = await Bun.file(path).text();
	out.push(`export const ${name} = ${JSON.stringify(raw)};`, "");
}
const dest = new URL("../src/lib/docs-content.ts", import.meta.url);
await Bun.write(dest, out.join("\n"));
