#!/bin/sh
. "${GPIO_EMU_STUBS}/_common.sh"
out=""
while [ "$#" -gt 0 ]; do
	if [ "$1" = "-o" ]; then
		shift
		out="$1"
	fi
	shift
done
if [ -z "$out" ]; then
	exit 1
fi
cat >"$out" <<EOF
#!/bin/sh
. "\${GPIO_EMU_STUBS}/_common.sh"
emu_hold "sketch"
EOF
chmod +x "$out"
exit 0
