#!/bin/sh
case "$1" in
service)
	echo active
	;;
auth)
	if [ "$2" = "pairing" ]; then
		echo "Token: emu-token"
		echo "https://t3-emu.gpio-companion.com/pair#token=emu-token"
	else
		echo "session present"
	fi
	;;
pair)
	echo "Token: emu-token"
	echo "https://t3-emu.gpio-companion.com/pair#token=emu-token"
	;;
*)
	echo ok
	;;
esac
exit 0
